# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'SSO-iOS-swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SSO-iOS-swift
  pod 'AFNetworking', '~> 3.0'
  pod 'IQKeyboardManager'
  pod 'CISSO'
end
